project:
  type: website
  output-dir: docs

website:
  title: "Espaço de Estados"
  site-url: https://raphateixeira.github.io/ControleEstados/
  repo-url: https://github.com/raphateixeira/ControleEstados
  
  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "Tópicos de Controle"
        contents:
          - Aulas/Aula00EspacoEstados.qmd

format:
  html:
    theme: 
      - default
      - TemaRTx.scss
    lang: pt-BR
    code-copy: true
    anchor-sections: true

  revealjs:
    theme: [default, TemaRTx.scss]
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/09/Logo_UFPA.png" # Opcional: logo da UFPA
    transition: slide
    slide-number: true
    footer: "Prof. Dr. Raphael Teixeira - UFPA"
    width: 1600
    height: 900
    code-theme: monokai
    code-font-size: 0.8em # Ajustado para não estourar o slide padrão
    code-line-numbers: true
    hash-type: number